project_id = "phybdsfwycygroebrsdx"

[functions.upload-to-lighthouse]
verify_jwt = false

[functions.check-copyright]
verify_jwt = false

[functions.deploy-artist-token]
verify_jwt = false

[functions.log-ip]
verify_jwt = false

[functions.create-feed-post]
verify_jwt = false

# Newly added admin functions (validate Privy JWT inside the function)
[functions.admin-get-verification-requests]
verify_jwt = false

[functions.admin-process-verification]
verify_jwt = false

[functions.admin-delete-song]
verify_jwt = false

[functions.admin-get-analytics]
verify_jwt = false

[functions.admin-delete-report]
verify_jwt = false

[functions.admin-update-song-ai-usage]
verify_jwt = false

# User action functions (likes, comments, reports) using Privy JWT validation
[functions.like-post]
verify_jwt = false

[functions.like-song]
verify_jwt = false

[functions.add-comment]
verify_jwt = false

[functions.report-song]
verify_jwt = false

[functions.update-song-token]
verify_jwt = false

[functions.upload-story]
verify_jwt = false

[functions.update-artist-profile]
verify_jwt = false

[functions.add-song-comment]
verify_jwt = false

[functions.ipfs-proxy]
verify_jwt = false

[functions.request-verification]
verify_jwt = false