project_id = "phybdsfwycygroebrsdx"

[functions.upload-to-lighthouse]
verify_jwt = false

[functions.check-copyright]
verify_jwt = false

[functions.deploy-artist-token]
verify_jwt = false

[functions.log-ip]
verify_jwt = false

[functions.create-feed-post]
verify_jwt = false